//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZ.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catogery
    {
        public Catogery()
        {
            this.CommonTypes = new HashSet<CommonType>();
        }
    
        public decimal ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CommonType> CommonTypes { get; set; }
    }
}
