//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZ.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonIssue
    {
        public CommonIssue()
        {
            this.Complaints = new HashSet<Complaint>();
        }
    
        public decimal ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Complaint> Complaints { get; set; }
    }
}
