//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZ.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ApartmentId { get; set; }
        public Nullable<decimal> Lvl1ID { get; set; }
        public Nullable<decimal> LVL2ID { get; set; }
        public Nullable<decimal> LVL3ID { get; set; }
        public Nullable<System.DateTime> AppointmentDateTime { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<decimal> Paint { get; set; }
        public Nullable<decimal> Status { get; set; }
        public string TechName { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public string Note { get; set; }
        public string Subject { get; set; }
        public Nullable<decimal> IssueId { get; set; }
        public string Id_Numer { get; set; }
        public string Phone { get; set; }
        public string Cutomer_Name { get; set; }
        public Nullable<decimal> Customer_Type { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual CommonItem CommonItem { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual CommonIssue CommonIssue { get; set; }
        public virtual Complaint Complaints1 { get; set; }
        public virtual Complaint Complaint1 { get; set; }
    }
}
