//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZ.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Complaints
    {
        public string Name { get; set; }
        public string flat { get; set; }
        public string Item { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> AppointmentDateTime { get; set; }
        public Nullable<decimal> Status { get; set; }
        public decimal ID { get; set; }
        public string cat { get; set; }
        public string type { get; set; }
        public string Note { get; set; }
        public string Subject { get; set; }
        public Nullable<decimal> Paint { get; set; }
        public string FullName { get; set; }
        public string Other { get; set; }
        public string StatusName { get; set; }
        public string OtherApartment { get; set; }
        public string Id_Numer { get; set; }
        public string Phone { get; set; }
        public Nullable<decimal> Customer_Type { get; set; }
        public string IssueId { get; set; }
        public string TechName { get; set; }
    }
}
