//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZ.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public decimal ID { get; set; }
        public string FullName { get; set; }
        public Nullable<decimal> IDType { get; set; }
        public Nullable<decimal> IDNumber { get; set; }
        public string Phone { get; set; }
        public Nullable<decimal> OwnershipType { get; set; }
        public Nullable<decimal> Gender { get; set; }
    }
}
