//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZ.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegularMaintence
    {
        public decimal ID { get; set; }
        public Nullable<System.DateTime> MaintenenceDate { get; set; }
        public Nullable<decimal> ItemId { get; set; }
        public Nullable<decimal> ItemCount { get; set; }
        public Nullable<decimal> TowerId { get; set; }
    }
}
